services:
    # PostgreSQL database service
    db:
        container_name: db
        image: postgis/postgis:17-3.4-alpine # Uses image of Postgres with Postgis extension
        platform: linux/amd64
        restart: unless-stopped # Always restart unless stopped manually'
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres-data:/var/lib/postgresql/data

    backend:
        container_name: backend
        image: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - NODE_ENV=development
        depends_on:
            - db # Make sure database is started before starting backend

volumes:
    postgres-data:
