services:
    # PostgreSQL database service
    db:
        container_name: db
        image: postgis/postgis # Uses base image of postgis 
        platform: linux/amd64
        restart: unless-stopped # Always restart unless stopped manually
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres-data:/var/lib/postgresql/data # Makes the database persistent

    backend:
        container_name: backend
        image: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        environment:
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
            - NODE_ENV=production
        depends_on:
            - db # Make sure database is started before starting backend

volumes:
    postgres-data:
